version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://techboyabhinav:91LD09PcbtVhtaln@cluster0.xudx3u9.mongodb.net/
      - JWT_SECRET=5bf0dc7b58b97c69aa671dd4ab06356d5633bd626ec15728438045d1c471ac98
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
